### ISSUE TITLE
Get Adam to review things

### ISSUE THREAD

**Issue by gappleto97** [gappleto97/p2p-project#50]
@ajacques

**Comment by ajacques** [comment]
?

**Comment by gappleto97** [comment]
Hey Adam,

Jason told me you might be willing to review some things. The big thing that I'm aware of right now is that the stuff in #33 either isn't quite implemented right, or my unit test is awful for it.

When I run the commands myself in separate console windows, I get errors 0/infinite times. When I run it from a unit test, it fails ~1/9 times.

Specifically I'm referring to [this test](https://github.com/gappleto97/p2p-project/blob/master/py_src/test/test_mesh.py#L88).

**Comment by gappleto97** [comment]
I can't make heads or tails of why it's failing so inconsistently.

The idea behind this is to test if a single connection fails. The two scenarios are 

1. It gets closed due to an error, and one of the nodes cleans it from their routing table
2. It gets closed for an unknown cause so nothing gets cleaned up

In the second case things can get messy.

Let's call the two affected nodes A and B. They have a common peer C.

When A and B notice that connection A<->B is broken, they each request C to give them its routing table. A and B then independently try to connect to each other. Upon handshake, they notice that there is an entry already in their routing table (from the other trying to reach them), so in order to keep things working, they each follow this rule:

If my ID is lower than theirs, I keep the incoming connection. Otherwise I keep the outgoing.
