### ISSUE TITLE
Investigate adding M2Crypto to ssl_wrapper

### ISSUE THREAD

**Issue by gappleto97** [gappleto97/p2p-project#52]

**Comment by drewfisher314** [comment]
I thought M2Crypto was abandoned/EOL?  Why not use cryptography.io?

**Comment by gappleto97** [comment]
If it is that's the first I've heard of it. Looking at their repo, last commit was yesterday.

As for not using cryptography.io, I'm more than willing to do so! As it happens, that's a dependency of PyOpenSSL anyhow.

All I really care about is this being as flexible as possible, so that people can use the libraries they want. As long as it doesn't cause a headache for me, I'll add support for any (secure) library people present to me.

**Comment by drewfisher314** [comment]
I was thinking PyCrypto.  Still, cryptography.io is probably a better choice than M2Crypto.

**Comment by gappleto97** [comment]
Probably. But my goal is to give developers choice in the matter. If the security is equal, and the implementation is easy, why not offer both options?

**Comment by gappleto97** [comment]
Just put a cryptography.io version on develop. Wanna make sure my unit tests pass (I can't test on every system myself), and it'd be great if I could have someone better with security look at it, but it works for me.

**Comment by gappleto97** [comment]
Near as I can tell M2Crypto has no usable docs. I'll check this again later if they add some.
